module.exports = [
  {
    bankTransactionId: null,
    name: 'Combe Incorporated',
    merchantName: null,
    amount: 136.75,
    date: '2021-08-11',
    userId: 2,
    categoryId: 1,
  },
  {
    bankTransactionId: null,
    name: 'Home Sweet Homeopathics',
    merchantName: null,
    amount: 836.93,
    date: '2021-05-03',
    userId: 2,
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'American Sales Company',
    merchantName: null,
    amount: 989.2,
    date: '2021-10-12',
    userId: 2,
    categoryId: 2,
  },
  {
    bankTransactionId: null,
    name: 'Cypress Pharmaceutical, Inc.',
    merchantName: null,
    amount: 399.84,
    date: '2021-12-31',
    userId: 1,
    categoryId: 2,
  },
  {
    bankTransactionId: null,
    name: 'Personal Care Products',
    merchantName: null,
    amount: 526.42,
    date: '2021-01-30',
    userId: 1,
    categoryId: 3,
  },
  {
    bankTransactionId: null,
    name: 'Bryant Ranch Prepack',
    merchantName: null,
    amount: 469.84,
    date: '2021-05-26',
    userId: 1,
    categoryId: 2,
  },
];
