module.exports = [
  {
    bankTransactionId: null,
    name: 'Chipotle',
    merchantName: null,
    amount: 2.0,
    date: '2021-10-28',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chicken Lovers',
    merchantName: null,
    amount: 5.3,
    date: '2021-10-29',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 2.63,
    date: '2021-11-01',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: "Wendy's",
    merchantName: null,
    amount: 2.66,
    date: '2021-11-18',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chicken Lovers',
    merchantName: null,
    amount: 7.32,
    date: '2021-11-29',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Burger King',
    merchantName: null,
    amount: 4.89,
    date: '2021-11-05',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Panera Bread',
    merchantName: null,
    amount: 8.95,
    date: '2021-11-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: "Wendy's",
    merchantName: null,
    amount: 9.73,
    date: '2021-11-21',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chicken Lovers',
    merchantName: null,
    amount: 3.33,
    date: '2021-10-30',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Popeyes',
    merchantName: null,
    amount: 7.39,
    date: '2021-11-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Corner 28',
    merchantName: null,
    amount: 2.43,
    date: '2021-11-20',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'McDonalds',
    merchantName: null,
    amount: 1.62,
    date: '2021-11-13',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Popeyes',
    merchantName: null,
    amount: 8.53,
    date: '2021-11-09',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 9.61,
    date: '2021-11-24',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: "Wendy's",
    merchantName: null,
    amount: 9.5,
    date: '2021-11-27',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Corner 28',
    merchantName: null,
    amount: 5.37,
    date: '2021-11-28',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chicken Lovers',
    merchantName: null,
    amount: 6.39,
    date: '2021-11-23',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Subway',
    merchantName: null,
    amount: 7.49,
    date: '2021-10-31',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 2.97,
    date: '2021-11-14',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chicken Lovers',
    merchantName: null,
    amount: 9.28,
    date: '2021-11-23',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Taco Bell',
    merchantName: null,
    amount: 6.2,
    date: '2021-11-17',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 4.8,
    date: '2021-11-27',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 3.52,
    date: '2021-11-28',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Popeyes',
    merchantName: null,
    amount: 8.84,
    date: '2021-11-01',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Panera Bread',
    merchantName: null,
    amount: 4.44,
    date: '2021-11-09',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: "Wendy's",
    merchantName: null,
    amount: 9.74,
    date: '2021-11-28',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'McDonalds',
    merchantName: null,
    amount: 4.03,
    date: '2021-11-22',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chicken Lovers',
    merchantName: null,
    amount: 6.5,
    date: '2021-11-27',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Taco Bell',
    merchantName: null,
    amount: 2.54,
    date: '2021-11-12',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Taco Bell',
    merchantName: null,
    amount: 2.82,
    date: '2021-10-28',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'McDonalds',
    merchantName: null,
    amount: 7.23,
    date: '2021-11-20',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Panera Bread',
    merchantName: null,
    amount: 9.68,
    date: '2021-11-21',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Popeyes',
    merchantName: null,
    amount: 1.33,
    date: '2021-10-28',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 5.03,
    date: '2021-10-30',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chicken Lovers',
    merchantName: null,
    amount: 7.64,
    date: '2021-11-25',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Panera Bread',
    merchantName: null,
    amount: 7.0,
    date: '2021-11-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Taco Bell',
    merchantName: null,
    amount: 9.98,
    date: '2021-10-28',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chipotle',
    merchantName: null,
    amount: 8.39,
    date: '2021-11-16',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chicken Lovers',
    merchantName: null,
    amount: 1.82,
    date: '2021-11-22',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Taco Bell',
    merchantName: null,
    amount: 1.88,
    date: '2021-11-03',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Taco Bell',
    merchantName: null,
    amount: 2.46,
    date: '2021-10-30',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Burger King',
    merchantName: null,
    amount: 2.38,
    date: '2021-11-13',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chicken Lovers',
    merchantName: null,
    amount: 6.76,
    date: '2021-11-20',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Burger King',
    merchantName: null,
    amount: 2.64,
    date: '2021-11-05',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: '99 Flavor Taste',
    merchantName: null,
    amount: 5.88,
    date: '2021-11-20',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'McDonalds',
    merchantName: null,
    amount: 9.28,
    date: '2021-11-12',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: '99 Flavor Taste',
    merchantName: null,
    amount: 2.95,
    date: '2021-10-31',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: '99 Flavor Taste',
    merchantName: null,
    amount: 2.35,
    date: '2021-11-18',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Panera Bread',
    merchantName: null,
    amount: 5.5,
    date: '2021-10-30',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'McDonalds',
    merchantName: null,
    amount: 3.72,
    date: '2021-11-09',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: '99 Flavor Taste',
    merchantName: null,
    amount: 8.67,
    date: '2021-11-27',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Panera Bread',
    merchantName: null,
    amount: 8.43,
    date: '2021-11-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: "Wendy's",
    merchantName: null,
    amount: 7.84,
    date: '2021-11-24',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 7.85,
    date: '2021-11-03',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chipotle',
    merchantName: null,
    amount: 5.57,
    date: '2021-11-29',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chipotle',
    merchantName: null,
    amount: 4.84,
    date: '2021-11-21',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Popeyes',
    merchantName: null,
    amount: 7.9,
    date: '2021-11-17',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 8.2,
    date: '2021-11-02',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Subway',
    merchantName: null,
    amount: 6.38,
    date: '2021-11-25',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Panera Bread',
    merchantName: null,
    amount: 9.02,
    date: '2021-10-31',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Burger King',
    merchantName: null,
    amount: 8.42,
    date: '2021-11-20',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 6.17,
    date: '2021-11-04',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Subway',
    merchantName: null,
    amount: 5.25,
    date: '2021-11-06',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Burger King',
    merchantName: null,
    amount: 1.12,
    date: '2021-11-05',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: '99 Flavor Taste',
    merchantName: null,
    amount: 1.78,
    date: '2021-10-29',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: "Wendy's",
    merchantName: null,
    amount: 6.66,
    date: '2021-11-04',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: '99 Flavor Taste',
    merchantName: null,
    amount: 2.55,
    date: '2021-11-27',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Panera Bread',
    merchantName: null,
    amount: 8.86,
    date: '2021-11-04',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Burger King',
    merchantName: null,
    amount: 8.76,
    date: '2021-11-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Subway',
    merchantName: null,
    amount: 9.06,
    date: '2021-11-11',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Subway',
    merchantName: null,
    amount: 2.88,
    date: '2021-10-28',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Taco Bell',
    merchantName: null,
    amount: 8.12,
    date: '2021-11-19',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 9.48,
    date: '2021-10-28',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chipotle',
    merchantName: null,
    amount: 6.88,
    date: '2021-11-23',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chicken Lovers',
    merchantName: null,
    amount: 7.6,
    date: '2021-11-09',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Burger King',
    merchantName: null,
    amount: 4.55,
    date: '2021-11-14',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'McDonalds',
    merchantName: null,
    amount: 8.84,
    date: '2021-11-20',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 7.66,
    date: '2021-11-09',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chipotle',
    merchantName: null,
    amount: 3.99,
    date: '2021-11-26',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Popeyes',
    merchantName: null,
    amount: 8.59,
    date: '2021-11-21',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: '99 Flavor Taste',
    merchantName: null,
    amount: 7.14,
    date: '2021-12-02',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Panera Bread',
    merchantName: null,
    amount: 8.51,
    date: '2021-12-06',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Popeyes',
    merchantName: null,
    amount: 9.17,
    date: '2021-12-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Popeyes',
    merchantName: null,
    amount: 9.44,
    date: '2021-12-07',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'McDonalds',
    merchantName: null,
    amount: 8.71,
    date: '2021-12-03',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'McDonalds',
    merchantName: null,
    amount: 9.34,
    date: '2021-12-03',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Chipotle',
    merchantName: null,
    amount: 8.57,
    date: '2021-12-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 7.67,
    date: '2021-12-04',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: "Wendy's",
    merchantName: null,
    amount: 8.18,
    date: '2021-12-03',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 7.15,
    date: '2021-12-01',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: "Wendy's",
    merchantName: null,
    amount: 7.55,
    date: '2021-12-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Taco Bell',
    merchantName: null,
    amount: 7.89,
    date: '2021-12-03',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Qdoba',
    merchantName: null,
    amount: 9.4,
    date: '2021-12-04',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Brooklyn Boulders',
    merchantName: null,
    amount: 33.57,
    date: '2021-10-31',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Dave & Busters',
    merchantName: null,
    amount: 26.83,
    date: '2021-11-24',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Cue Bar',
    merchantName: null,
    amount: 34.87,
    date: '2021-11-13',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Cue Bar',
    merchantName: null,
    amount: 39.76,
    date: '2021-10-29',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Cue Bar',
    merchantName: null,
    amount: 36.2,
    date: '2021-11-13',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Douglaston Golf Center',
    merchantName: null,
    amount: 34.06,
    date: '2021-11-27',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Paintball',
    merchantName: null,
    amount: 28.68,
    date: '2021-11-20',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Paintball',
    merchantName: null,
    amount: 28.46,
    date: '2021-11-19',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Lucky Strike',
    merchantName: null,
    amount: 28.85,
    date: '2021-11-05',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Jib Lanes',
    merchantName: null,
    amount: 27.63,
    date: '2021-11-11',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Brooklyn Boulders',
    merchantName: null,
    amount: 39.75,
    date: '2021-11-17',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Museum of Modern Arts',
    merchantName: null,
    amount: 38.88,
    date: '2021-11-13',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Cue Bar',
    merchantName: null,
    amount: 23.7,
    date: '2021-11-08',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Lucky Strike',
    merchantName: null,
    amount: 29.11,
    date: '2021-11-12',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Cue Bar',
    merchantName: null,
    amount: 35.21,
    date: '2021-11-10',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Lucky Strike',
    merchantName: null,
    amount: 31.71,
    date: '2021-12-01',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Paintball',
    merchantName: null,
    amount: 28.64,
    date: '2021-12-05',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Museum of Modern Art',
    merchantName: null,
    amount: 26.19,
    date: '2021-12-03',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Cue Bar',
    merchantName: null,
    amount: 23.52,
    date: '2021-12-05',
    categoryId: 8,
  },
  {
    bankTransactionId: null,
    name: 'Nike Manhattan',
    merchantName: null,
    amount: 50.76,
    date: '2021-12-02',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Adidas',
    merchantName: null,
    amount: 53.92,
    date: '2021-12-08',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'UNIQLO NYC',
    merchantName: null,
    amount: 32.02,
    date: '2021-12-04',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Adidas',
    merchantName: null,
    amount: 59.71,
    date: '2021-12-03',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Adidas',
    merchantName: null,
    amount: 32.31,
    date: '2021-12-08',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Nike Manhattan',
    merchantName: null,
    amount: 34.33,
    date: '2021-12-08',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Adidas',
    merchantName: null,
    amount: 54.26,
    date: '2021-12-04',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Hot Topic',
    merchantName: null,
    amount: 62.82,
    date: '2021-12-01',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Hot Topic',
    merchantName: null,
    amount: 35.05,
    date: '2021-12-08',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Best Buy',
    merchantName: null,
    amount: 68.46,
    date: '2021-12-02',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Target',
    merchantName: null,
    amount: 55.05,
    date: '2021-11-22',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'American Eagle',
    merchantName: null,
    amount: 51.89,
    date: '2021-11-07',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Costco',
    merchantName: null,
    amount: 52.2,
    date: '2021-10-31',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'UNIQLO NYC',
    merchantName: null,
    amount: 63.93,
    date: '2021-11-27',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Target',
    merchantName: null,
    amount: 31.3,
    date: '2021-11-01',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Walmart',
    merchantName: null,
    amount: 69.5,
    date: '2021-11-14',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Pacsun Queens Center',
    merchantName: null,
    amount: 49.81,
    date: '2021-11-07',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Yankee Candle',
    merchantName: null,
    amount: 34.79,
    date: '2021-11-24',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Walmart',
    merchantName: null,
    amount: 34.81,
    date: '2021-11-28',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Urban Outfitters',
    merchantName: null,
    amount: 37.42,
    date: '2021-10-31',
    categoryId: 10,
  },
  {
    bankTransactionId: null,
    name: 'Lyft',
    merchantName: null,
    amount: 20.25,
    date: '2021-11-30',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'NYC OMNY',
    merchantName: null,
    amount: 27.57,
    date: '2021-11-30',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'NYC OMNY',
    merchantName: null,
    amount: 28.07,
    date: '2021-11-30',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'Lyft',
    merchantName: null,
    amount: 27.59,
    date: '2021-11-30',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'Uber Pool',
    merchantName: null,
    amount: 21.39,
    date: '2021-11-30',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'NYC OMNY',
    merchantName: null,
    amount: 14.75,
    date: '2021-11-30',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'Uber NYC',
    merchantName: null,
    amount: 26.51,
    date: '2021-11-30',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'Lyft',
    merchantName: null,
    amount: 25.05,
    date: '2021-11-30',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'Uber NYC',
    merchantName: null,
    amount: 17.97,
    date: '2021-12-06',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'NYC OMNY',
    merchantName: null,
    amount: 26.41,
    date: '2021-12-05',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'NYC OMNY',
    merchantName: null,
    amount: 15.25,
    date: '2021-12-02',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'Uber NYC',
    merchantName: null,
    amount: 29.45,
    date: '2021-12-03',
    categoryId: 13,
  },
  {
    bankTransactionId: null,
    name: 'Bellerose Laundromat',
    merchantName: null,
    amount: 23.63,
    date: '2021-12-05',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: "James' Landscaping Corp",
    merchantName: null,
    amount: 28.6,
    date: '2021-12-02',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: 'Union Turnpike Laundromat',
    merchantName: null,
    amount: 20.28,
    date: '2021-12-06',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: 'Union Turnpike Laundromat',
    merchantName: null,
    amount: 39.01,
    date: '2021-12-01',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: "James' Landscaping Corp",
    merchantName: null,
    amount: 23.41,
    date: '2021-11-29',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: 'Douglaston Auto Care',
    merchantName: null,
    amount: 34.2,
    date: '2021-11-19',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: 'Union Turnpike Laundromat',
    merchantName: null,
    amount: 30.82,
    date: '2021-11-04',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: 'Union Turnpike Laundromat',
    merchantName: null,
    amount: 25.01,
    date: '2021-11-22',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: 'Douglaston Auto Care',
    merchantName: null,
    amount: 39.04,
    date: '2021-11-05',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: 'Bellerose Laundromat',
    merchantName: null,
    amount: 36.05,
    date: '2021-11-24',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: "James' Landscaping Corp",
    merchantName: null,
    amount: 34.43,
    date: '2021-11-10',
    categoryId: 9,
  },
  {
    bankTransactionId: null,
    name: 'CityMD Elmhurst',
    merchantName: null,
    amount: 69.41,
    date: '2021-11-19',
    categoryId: 5,
  },
  {
    bankTransactionId: null,
    name: 'Jay Ledner DDS PLLC & Associates',
    merchantName: null,
    amount: 62.47,
    date: '2021-11-12',
    categoryId: 5,
  },
  {
    bankTransactionId: null,
    name: 'CVS Pharmaceuticals',
    merchantName: null,
    amount: 69.11,
    date: '2021-11-22',
    categoryId: 5,
  },
  {
    bankTransactionId: null,
    name: 'CVS Pharmaceuticals',
    merchantName: null,
    amount: 80.27,
    date: '2021-12-04',
    categoryId: 5,
  },
  {
    bankTransactionId: null,
    name: 'Rent',
    merchantName: null,
    amount: 1800,
    date: '2021-10-01',
    categoryId: 7,
  },

  {
    bankTransactionId: null,
    name: 'Rent',
    merchantName: null,
    amount: 600,
    date: '2021-12-01',
    categoryId: 7,
  },
  {
    bankTransactionId: null,
    name: 'Rent',
    merchantName: null,
    amount: 1800,
    date: '2021-11-01',
    categoryId: 7,
  },
  {
    bankTransactionId: null,
    name: 'Rent',
    merchantName: null,
    amount: 1800,
    date: '2021-10-01',
    categoryId: 7,
  },

  {
    bankTransactionId: null,
    name: 'Bryant Ranch Prepack',
    merchantName: null,
    amount: 3840,
    date: '2021-09-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Bryant Ranch Prepack',
    merchantName: null,
    amount: 3900,
    date: '2021-08-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Bryant Ranch Prepack',
    merchantName: null,
    amount: 3750,
    date: '2021-07-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Bryant Ranch Prepack',
    merchantName: null,
    amount: 4150,
    date: '2021-06-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Bryant Ranch Prepack',
    merchantName: null,
    amount: 4220,
    date: '2021-05-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Bryant Ranch Prepack',
    merchantName: null,
    amount: 4300,
    date: '2021-04-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Bryant Ranch Prepack',
    merchantName: null,
    amount: 4100,
    date: '2021-03-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Bryant Ranch Prepack',
    merchantName: null,
    amount: 4050,
    date: '2021-02-08',
    categoryId: 4,
  },
  {
    bankTransactionId: null,
    name: 'Bryant Ranch Prepack',
    merchantName: null,
    amount: 4375,
    date: '2021-01-08',
    categoryId: 4,
  },
];
